version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "4023:80"  # Map container port 80 to host port 3000
    environment:
      - VITE_API_URL=${API_URL:-https://api.example.com}
    depends_on:
      - server
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8001:8000"  # Map container port 8000 to host port 8001
    environment:
      - CHAT_APP_URL=${CLIENT_URL:-https://example.com}
      - STREAM_API_KEY=${STREAM_API_KEY}
      - STREAM_API_SECRET=${STREAM_API_SECRET}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: always 